### ISSUE TITLE
Investigate non-deterministic test failures in testutil/network/network.go

### ISSUE THREAD

**Issue by zramsay** [cerc-io/laconicd#104]
Follow up from https://github.com/cerc-io/laconicd/pull/74#pullrequestreview-1240987800  and showed up in #102.

See: https://github.com/cerc-io/laconicd/runs/12015779774
And, e.g., https://github.com/cerc-io/laconicd/security/code-scanning/

**Comment by 0xmuralik** [comment]
The mutex lock is being released in the clean up func and is not recognized by semgrep. I think this is a false positive.
https://github.com/cerc-io/laconicd/blob/main/testutil/network/network.go#L611
