### ISSUE TITLE
TEST_AUCTION_ENABLED is clunky

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconicd#106]
Since the laconicd process has to be started in TEST_AUCTION_ENABLED mode in order to run some tests, this makes CI cumbersome -- the restart process takes time, and test code has to keep track of which mode the process has been run in. It would be better if the test conditions could be injected from outside on an already running process.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/laconicd/issues/106
