### ISSUE TITLE
Registry type definitions are done with protocol buffers schema 

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconicd#108]
Registry record type definitions (schema) are currently in the form of `.proto` files [here](https://github.com/cerc-io/laconicd/blob/a5681191a58f7709a6072d886802c4a5bb55919c/proto/vulcanize/registry/v1beta1/attributes.proto#L8).

While the protocol buffers schema format has the functionality required, it's inconsistent with the overall project goal to use IPLD tech.

Therefore these schema definitions should instead use [IPLD Schemas](https://ipld.io/docs/schemas/using/authoring-guide/).

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/laconicd/issues/108
