### ISSUE TITLE
Integrate cosmwasm module into laconicd

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#25]
From Ashwin: Integrate the latest cosmwasm module into chiba-clonk, enabling us to run cosmwasm contracts on chain.

- [x] <s>Refactor cosmwasm stack onto SDK+SMT</s>
- [ ] Update laconicd to load the cosmwasm module into the BaseApp
- [ ] Deploy a  CosmWASM contract and run it in the testnet

**Comment by i-norden** [comment]
To be able to run small pieces of warm to run. 

Off chain someone runs watcher, claims state root of watcher at certain height.

If someone wants to contest, they send a tx to laconic claiming an operation produced the wrong result.

On chain, we execute a small portion of the watcher execution graph (within the cosmwasm execution environment) to see that the state root produced is not as expected.

For fraud proofs in the responder group, at the L3.

**Comment by i-norden** [comment]
TODO:

- [ ] Port wasmd x/ module here, fix any dependency related breaks
- [ ] Set so that no accounts are authorized to `create`
- [ ] Create new `eval` keeper method that accepts WASM bytes, executes them, returns result without storing code or result in state
- [ ] Provided to this method is not the WASM itself, but a reference to registry record containing the registered WASM (must register before evaluating)
- [ ] If we can cleanly cut out the unused code paths we should, but if it disrupts the remaining code such that rebasing on future releases is complicated we may want to leave them as vestigial pieces
- [ ]

**Comment by AFDudley** [comment]
Should this issue be closed?

**Comment by i-norden** [comment]
@AFDudley this work has not been completed yet.

**Comment by AFDudley** [comment]
I think your edits addressed my concerns, thank you.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/laconicd/issues/25
