### ISSUE TITLE
Rollback tendermint version to v0.34.21

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#37]
Rollback to https://github.com/tendermint/tendermint/releases/tag/v0.34.21. v0.35.x has been deprecated, and Sjors has identified this is the likely cause to our node stability issues.

**Comment by 0xmuralik** [comment]
The forked version of cosmos-sdk uses tendermint v0.35.
https://github.com/cerc-io/cosmos-sdk/blob/1d68820c575878f901af43eb324a1fe8debd2467/go.mod#L49
We'll have to replace this first to fix this issue.
