### ISSUE TITLE
Verify new published container image

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconicd#45]

**Comment by dboreham** [comment]
https://git.vdb.to/cerc-io/-/packages/container/laconicd%2Flaconicd/v0.6.0

**Comment by dboreham** [comment]
Smoke tested the published container by specifying its URL as the base image for a laconic-so laconicd fixturenet.
This started up successfully and generated blocks:

```
8:22PM INF received complete proposal block hash=8F91BC43B2E7A858ADF741F64FCE19B5682EADD72BD7486D361DA6B3653421B1 height=3 module=consensus server=node
8:22PM INF finalizing commit of block hash={} height=3 module=consensus num_txs=0 root=FBFF3F705CDB5048B70407501DEC77593F39EFE1CDCB9DE56B288E3BDE537413 server=node
8:22PM INF minted coins from module account amount=2059726771778267119aphoton from=mint module=x/bank
8:22PM INF executed block height=3 module=state num_invalid_txs=0 num_valid_txs=0 server=node
8:22PM INF commit synced commit=436F6D6D697449447B5B3634203535203530203132352031373420393920323330203138362032303620313735203138322032303920322031333420323036203433203730203131382032333120333720323620373920323333203233372034352038302031393320313436203136312032333220323533203135325D3A337D
8:22PM INF committed state app_hash=4037327DAE63E6BACEAFB6D10286CE2B4676E7251A4FE9ED2D50C192A1E8FD98 height=3 module=state num_txs=0 server=node
8:22PM INF indexed block height=3 module=txindex server=node
```

**Comment by dboreham** [comment]
The [sdk test suite](https://github.com/cerc-io/laconic-sdk#tests) is failing for me against the container image:

```
Test Suites: 5 failed, 2 passed, 7 total
Tests:       30 failed, 10 passed, 40 total
Snapshots:   0 total
Time:        63.002 s
Ran all test suites.
```

_However_, the tests fail in the same way run against a local build of the current main branch laconicd code, so I think the container image is therefore still valid.

**Comment by dboreham** [comment]
@ABastionOfSanity

**Comment by i-norden** [comment]
Perhaps this is caused by https://github.com/cerc-io/laconicd/pull/43#discussion_r1006620569?

**Comment by dboreham** [comment]
> Perhaps this is caused by [#43 (comment)](https://github.com/cerc-io/laconicd/pull/43#discussion_r1006620569)?

Not directly, because I'm running a different test suite that's external to the laconicd project itself.
