### ISSUE TITLE
laconic-sdk tests in CI

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#46]
Run [laconic-sdk](https://github.com/cerc-io/laconic-sdk#tests) test suite against laconicd docker image in CI.

The plan here is to add laconic-sdk as a repo dependency in the CI environment, the CI will build the tests from there and run them against the new version of laconicd.

Run these tests on PRs to main and releases.

**Comment by i-norden** [comment]
@ABastionOfSanity in light of https://github.com/cerc-io/laconic-sdk/issues/8 figuring out how to run the laconic-sdk tests in CI is pretty high priority imo

**Comment by i-norden** [comment]
Have CD for a container that incorporates the built cosmos-sdk, such that anybody can pull that container with the `latest` tag and execute with a `docker run` command. 

This will work unless you are making breaking changes on laconicd, which require changes to comsos-sdk. For this scenario it would be helpful to be able to target the CD to a specific commit/branch/release of laconicd.

**Comment by dboreham** [comment]
See: https://github.com/cerc-io/laconicd/pull/71

**Comment by ABastionOfSanity** [comment]
Tests pass locally, but failing in CI is masked by docker logs output.

**Comment by ABastionOfSanity** [comment]
Doubling bond in naming tests from sdk side get tests passing.
