### ISSUE TITLE
Dynamic attribute indexing cont.

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#52]
#40 introduced record indexing and searching by attributes, currently for WebstieRegistration and ServiceProviderRegistration record types.

We need to

1. Extend the current "hard-coded" approach to the remaining record types https://github.com/cerc-io/laconicd/issues/51
2. Devise a scheme for providing attribute indexing to unknown/arbitrary types.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/laconicd/issues/52
