### ISSUE TITLE
Implement a registry viewer/query UI

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconicd#56]
Allow Laconic-hosted services to be discovered interactively through a web interface that queries the registry, displaying clickable results that allow navigation to the relevant service endpoints.

**Comment by rickmanelius** [comment]
Part of the motivation for this ticket stemmed from [this Slack thread](https://atomicform.slack.com/archives/C03QRU66JSW/p1669051466531229) referencing [this Tweet](https://twitter.com/ajlamarc/status/1594508868427698178) about a "Self-hosted 
[@Uniswap](https://twitter.com/Uniswap) frontend on Urbit 🦄🚀"

**Comment by AFDudley** [comment]
I'm assuming we can do a relatively light port of
https://github.com/dxos/console

We should be able to support things we already have in production that need to be registered, this is not a complete list:

* watcher source
* watcher bytecode
* watcher endpoints
* DNS entities
* git repositories
* npm repositories
* npm packages
* docker images
* legal entities with DIDs
