### ISSUE TITLE
Refactor getReference in GQL

### ISSUE THREAD

**Issue by 0xmuralik** [cerc-io/laconicd#78]
Prior to the Record attribute typing, each CID value was reffered with a "/".
Ex: https://github.com/cerc-io/laconicd/blob/main/x/registry/helpers/examples/example1.yml

Now it's changed to https://github.com/cerc-io/laconicd/blob/main/x/registry/helpers/examples/service_provider_example.yml
Refactor [getReferences](https://github.com/cerc-io/laconicd/blob/ab2ea51aac6e3c26a41dd4028d8d5d8884e13b50/gql/util.go#L166) to work with new types of attributes.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/laconicd/issues/78
