### ISSUE TITLE
Review/clean up Makefile

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#82]
Our Makefile was inherited from ethermint, which was inherited from cosmos-sdk, and adjusted ad hoc to our needs.

We need to perform a review of the Makefile and clean out any unused utilities and adjust things to our liking.

**Comment by i-norden** [comment]
Also provide better documentation for what the commands are doing

**Comment by zramsay** [comment]
if `make build` / `make install` is giving you problems installing the version you want, try `go install ./...`

**Comment by ABastionOfSanity** [comment]
goreleaser is high on my list for this.  I think it can be removed.
