### ISSUE TITLE
Implement `CIDFromJSONBytesUsingIpldPrime`

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconicd#85]
Using https://github.com/ipld/go-ipld-prime/blob/master/codec/dagcbor/marshal.go#L36

Currently it uses a linksystem which is unnecessary and overcomplicates the code and makes it harder to understand what is happening.

**Comment by ABastionOfSanity** [comment]
closed by:
https://github.com/cerc-io/laconicd/pull/88
